import { useIdioma } from "~/modules/idiomas/idioma";
const ko: Record<string, string> = {
  movida: "이동됨",
  checklist: "체크리스트 변경",
  arquivada: "보관됨",
  Cópias: "참조",
  "Pessoa em cópia": "참조 사용자",
  "Adicionar cópia": "참조 추가",
  "Remover cópia": "참조 제거",
  Quadros: "보드",
  "Meu Quadro": "내 보드",
  Novo: "새 작업",
  "Em foco": "집중",
  Aguardando: "대기 중",
  Concluído: "완료",
  "Criar Quadro": "보드 만들기",
  Nome: "이름",
  "Criar lista": "목록 만들기",
  "Criar tarefa": "작업 만들기",
  Título: "제목",
  Prazo: "기한",
  Lista: "목록",
  Mover: "이동",
  "Abrir Quadro": "보드 열기",
  Arquivar: "보관",
  Renomear: "이름 변경",
  Compartilhar: "공유",
  "Remover membro": "멤버 제거",
  Pessoa: "사용자",
  "Conversa da tarefa": "작업 대화",
  Checklist: "체크리스트",
  "Adicionar item": "항목 추가",
  Marcar: "선택",
  Desmarcar: "해제",
  "Promover a tarefa": "작업으로 승격",
  "Enviar tarefa": "작업 전달",
  Responsável: "담당자",
  Etiquetas: "라벨",
  "Criar etiqueta": "라벨 만들기",
  Atribuir: "추가",
  Remover: "제거",
  Anexos: "첨부 파일",
  Anexar: "첨부",
  "Usar como capa": "표지로 사용",
  Capa: "표지",
  Pesquisar: "검색",
  Filtrar: "필터",
  Todas: "전체",
  Viagem: "여행",
  "Sem prazo": "기한 없음",
  Atrasadas: "기한 초과",
  Hoje: "오늘",
  "Ocultar concluídas": "완료 숨기기",
  Calendário: "달력",
  Listas: "목록",
  Arquivado: "보관됨",
  "Lista de conclusão": "완료 목록",
  "Sem lista de conclusão": "완료 목록 없음",
  Subir: "위로",
  Descer: "아래로",
  Salvar: "저장",
  "Mostrar arquivadas": "보관된 목록 표시",
  "Tarefa de origem": "원래 작업",
  "Falha ao salvar": "저장 실패",
  Membros: "멤버",
  "Abrir tarefa": "작업 열기",
  Descrição: "설명",
  Arquivo: "파일",
  Anterior: "이전",
  Próximo: "다음",
  "Modelos de etapa": "단계 템플릿",
};
export function useQuadrosTexto() {
  const { idioma } = useIdioma();
  return (s: string) =>
    idioma === "ko"
      ? (ko[s] ?? s)
      : ({
          movida: "Movida",
          checklist: "Checklist atualizado",
          arquivada: "Arquivada",
        }[s as "movida"] ?? s);
}
