CREATE TABLE "tabelas_referencia" (
	"codigo" text PRIMARY KEY NOT NULL,
	"titulo" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "versoes_referencia" (
	"id" serial PRIMARY KEY NOT NULL,
	"tabela" text NOT NULL,
	"versao" integer NOT NULL,
	"dados" jsonb NOT NULL,
	"autor_id" integer,
	"criada_em" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "versoes_referencia" ADD CONSTRAINT "versoes_referencia_tabela_tabelas_referencia_codigo_fk" FOREIGN KEY ("tabela") REFERENCES "public"."tabelas_referencia"("codigo") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "versoes_referencia" ADD CONSTRAINT "versoes_referencia_autor_id_usuarios_id_fk" FOREIGN KEY ("autor_id") REFERENCES "public"."usuarios"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "versoes_referencia_tabela_versao_idx" ON "versoes_referencia" USING btree ("tabela","versao");
--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('equipe','Guia e Assistente');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('equipe',1,'{"colunas":[{"chave":"guia","nome":"Guia USD","tipo":"numero"},{"chave":"assistente","nome":"Assistente USD","tipo":"numero"}],"linhas":[{"id":"operadora","nome":"Interep/Operadora","guia":260,"assistente":180},{"id":"agencia","nome":"Agência","guia":290,"assistente":200},{"id":"cliente_final","nome":"Cliente final","guia":320,"assistente":220},{"id":"influencer","nome":"Influencer","guia":320,"assistente":220}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('temporada_corealux','Temporada CoreaLux');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('temporada_corealux',1,'{"colunas":[{"chave":"inicio","nome":"Início (MM-DD)","tipo":"texto"},{"chave":"fim","nome":"Fim (MM-DD)","tipo":"texto"},{"chave":"fator","nome":"Fator","tipo":"numero"}],"linhas":[{"id":"faixa0","nome":"Alta","inicio":"03-25","fim":"05-31","fator":1.2},{"id":"faixa1","nome":"Alta","inicio":"07-15","fim":"08-17","fator":1.2},{"id":"faixa2","nome":"Alta","inicio":"09-26","fim":"10-31","fator":1.2},{"id":"faixa3","nome":"Alta","inicio":"12-20","fim":"01-14","fator":1.2},{"id":"faixa4","nome":"Média","inicio":"03-15","fim":"03-24","fator":1.1},{"id":"faixa5","nome":"Média","inicio":"06-01","fim":"06-15","fator":1.1},{"id":"faixa6","nome":"Média","inicio":"09-05","fim":"09-25","fator":1.1},{"id":"faixa7","nome":"Baixa","inicio":"01-15","fim":"03-14","fator":0.9},{"id":"faixa8","nome":"Baixa","inicio":"06-20","fim":"07-14","fator":0.9},{"id":"faixa9","nome":"Baixa","inicio":"08-18","fim":"09-04","fator":0.9},{"id":"faixa10","nome":"Baixa","inicio":"11-20","fim":"12-10","fator":0.9},{"id":"faixa11","nome":"Base","inicio":"06-16","fim":"06-19","fator":1},{"id":"faixa12","nome":"Base","inicio":"11-01","fim":"11-19","fator":1},{"id":"faixa13","nome":"Base","inicio":"12-11","fim":"12-19","fator":1}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('temporada_jeju','Temporada de voos Jeju');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('temporada_jeju',1,'{"colunas":[{"chave":"inicio","nome":"Início (MM-DD)","tipo":"texto"},{"chave":"fim","nome":"Fim (MM-DD)","tipo":"texto"},{"chave":"fator","nome":"Fator","tipo":"numero"}],"linhas":[{"id":"faixa0","nome":"Alta","inicio":"07-01","fim":"08-31","fator":1},{"id":"faixa1","nome":"Alta","inicio":"03-15","fim":"05-15","fator":1}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('temporada_onibus','Temporada do fornecedor de ônibus');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('temporada_onibus',1,'{"colunas":[{"chave":"inicio","nome":"Início (MM-DD)","tipo":"texto"},{"chave":"fim","nome":"Fim (MM-DD)","tipo":"texto"},{"chave":"fator","nome":"Fator","tipo":"numero"}],"linhas":[{"id":"faixa0","nome":"Baixa","inicio":"07-01","fim":"08-31","fator":0.9},{"id":"faixa1","nome":"Baixa","inicio":"12-01","fim":"02-ultimo","fator":0.9},{"id":"faixa2","nome":"Alta","inicio":"03-01","fim":"06-30","fator":1.2},{"id":"faixa3","nome":"Alta","inicio":"09-01","fim":"11-30","fator":1.2}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('feriados','Feriados nacionais coreanos');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('feriados',1,'{"colunas":[{"chave":"inicio","nome":"Início","tipo":"data"},{"chave":"fim","nome":"Fim","tipo":"data"},{"chave":"fonte","nome":"Fonte","tipo":"texto"}],"linhas":[{"id":"2026-0","nome":"Ano Novo 2026","inicio":"2026-01-01","fim":"2026-01-01","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-1","nome":"Seollal 2026","inicio":"2026-02-16","fim":"2026-02-18","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-2","nome":"Movimento de Independência 2026","inicio":"2026-03-01","fim":"2026-03-02","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-3","nome":"Dia das Crianças 2026","inicio":"2026-05-05","fim":"2026-05-05","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-4","nome":"Aniversário de Buda 2026","inicio":"2026-05-24","fim":"2026-05-25","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-5","nome":"Eleições locais 2026","inicio":"2026-06-03","fim":"2026-06-03","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-6","nome":"Memorial 2026","inicio":"2026-06-06","fim":"2026-06-06","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-7","nome":"Constituição 2026","inicio":"2026-07-17","fim":"2026-07-17","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-8","nome":"Libertação 2026","inicio":"2026-08-15","fim":"2026-08-15","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-9","nome":"Libertação (substituto) 2026","inicio":"2026-08-17","fim":"2026-08-17","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-10","nome":"Chuseok 2026","inicio":"2026-09-24","fim":"2026-09-26","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-11","nome":"Fundação Nacional 2026","inicio":"2026-10-03","fim":"2026-10-03","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-12","nome":"Fundação Nacional (substituto) 2026","inicio":"2026-10-05","fim":"2026-10-05","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-13","nome":"Hangul 2026","inicio":"2026-10-09","fim":"2026-10-09","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"},{"id":"2026-14","nome":"Natal 2026","inicio":"2026-12-25","fim":"2026-12-25","fonte":"https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140045"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('eventos','Eventos especiais');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('eventos',1,'{"colunas":[{"chave":"inicio","nome":"Início","tipo":"data"},{"chave":"fim","nome":"Fim","tipo":"data"},{"chave":"adicional","nome":"Adicional sobre guia e carro","tipo":"numero"}],"linhas":[]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('frota','Frota e tarifas');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('frota',1,'{"colunas":[{"chave":"operadora","nome":"Operadora USD","tipo":"numero"},{"chave":"agencia","nome":"Agência USD","tipo":"numero"},{"chave":"cliente_final","nome":"Cliente final USD","tipo":"numero"},{"chave":"assentos","nome":"Assentos físicos","tipo":"numero"},{"chave":"conforto","nome":"Clientes com conforto","tipo":"numero"},{"chave":"motorista","nome":"Motorista","tipo":"texto"}],"linhas":[{"id":"spark","nome":"Spark próprio","operadora":120,"agencia":130,"cliente_final":150,"assentos":5,"conforto":3,"motorista":"guia","provisorio":"Confirmar configuração do veículo"},{"id":"tucson","nome":"Tucson próprio","operadora":120,"agencia":130,"cliente_final":150,"assentos":5,"conforto":3,"motorista":"guia","provisorio":"Confirmar configuração do veículo"},{"id":"carnival_propria","nome":"Carnival própria","operadora":null,"agencia":null,"cliente_final":null,"assentos":null,"conforto":4,"motorista":"guia"},{"id":"sedan","nome":"Sedan externo","operadora":180,"agencia":190,"cliente_final":200,"assentos":5,"conforto":2,"motorista":"incluído","provisorio":"Assentos a confirmar no veículo efetivo"},{"id":"carnival","nome":"Kia Carnival externa","operadora":210,"agencia":220,"cliente_final":230,"assentos":9,"conforto":4,"motorista":"incluído","provisorio":"Assentos a confirmar no veículo efetivo"},{"id":"staria","nome":"Hyundai Staria","operadora":210,"agencia":220,"cliente_final":230,"assentos":11,"conforto":6,"motorista":"incluído","provisorio":"Assentos a confirmar no veículo efetivo"},{"id":"solati","nome":"Hyundai Solati","operadora":290,"agencia":310,"cliente_final":340,"assentos":15,"conforto":8,"motorista":"incluído","provisorio":"Assentos a confirmar no veículo efetivo"},{"id":"sprinter","nome":"Mercedes Sprinter","operadora":370,"agencia":400,"cliente_final":450,"assentos":13,"conforto":11,"motorista":"incluído","provisorio":"Assentos a confirmar no veículo efetivo"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('transfers','Transfers');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('transfers',1,'{"colunas":[{"chave":"simples","nome":"Só deixar/pegar USD","tipo":"numero"},{"chave":"recepcao","nome":"Funcionário USD","tipo":"numero"},{"chave":"placa","nome":"Motorista com placa USD","tipo":"numero"},{"chave":"checkin","nome":"Check-in USD","tipo":"numero"},{"chave":"onibus","nome":"Ônibus USD","tipo":"numero"}],"linhas":[{"id":"gimpo","nome":"Gimpo ↔ hotel Seul","simples":50,"recepcao":80,"placa":80,"checkin":90,"onibus":300},{"id":"incheon","nome":"Incheon ↔ hotel Seul","simples":100,"recepcao":150,"placa":120,"checkin":150,"onibus":350},{"id":"gimhae","nome":"Gimhae ↔ hotel Busan","simples":100,"recepcao":150,"placa":120,"checkin":150,"onibus":350},{"id":"jeju_city","nome":"Jeju ↔ Jeju City","simples":40,"recepcao":null,"placa":60,"checkin":80,"onibus":200},{"id":"seogwipo","nome":"Jeju ↔ Seogwipo","simples":100,"recepcao":null,"placa":120,"checkin":140,"onibus":300},{"id":"estacao_seul","nome":"Hotel ↔ estação Seul","simples":40,"recepcao":40,"placa":60,"checkin":null,"onibus":150},{"id":"estacao_busan","nome":"Hotel ↔ estação Busan/Gyeongju","simples":60,"recepcao":60,"placa":60,"checkin":null,"onibus":150},{"id":"gyeongju_busan","nome":"Gyeongju ↔ Busan","simples":100,"recepcao":100,"placa":100,"checkin":100,"onibus":300}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('tickets','Ingressos e transportes');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('tickets',1,'{"colunas":[{"chave":"valor","nome":"Valor","tipo":"numero"},{"chave":"unidade","nome":"Unidade","tipo":"texto"}],"linhas":[{"id":"dmz","nome":"DMZ","valor":20,"unidade":"USD"},{"id":"san","nome":"Museu SAN","valor":60,"unidade":"USD"},{"id":"sayuwon","nome":"Sayuwon","valor":60,"unidade":"USD"},{"id":"jeju_premium","nome":"Jeju atração premium","valor":40,"unidade":"USD"},{"id":"haenyeo","nome":"Haenyeo Kitchen (inclui guia)","valor":70,"unidade":"USD"},{"id":"sky_capsule","nome":"Sky Capsule / até 4 pessoas","valor":60,"unidade":"USD"},{"id":"especial","nome":"Atração especial","valor":30,"unidade":"USD"},{"id":"duas_especiais","nome":"Duas atrações especiais","valor":60,"unidade":"USD"},{"id":"ktx_economica","nome":"KTX econômica","valor":70,"unidade":"USD"},{"id":"ktx_executiva","nome":"KTX executiva","valor":100,"unidade":"USD"},{"id":"bagagem_trecho","nome":"Transporte separado de bagagem / pessoa","valor":30,"unidade":"USD"},{"id":"caminhao_icn","nome":"Caminhão ICN ↔ Seul","valor":150,"unidade":"USD"},{"id":"voo_bagagem","nome":"Voo: 5 kg adicionais","valor":10,"unidade":"USD"},{"id":"jeju_alta","nome":"Jeju alta / sex–dom","valor":100,"unidade":"USD"},{"id":"jeju_quinta","nome":"Jeju quinta","valor":80,"unidade":"USD"},{"id":"jeju_baixa","nome":"Jeju seg–qua","valor":60,"unidade":"USD"},{"id":"pernoite_equipe","nome":"Pernoite da equipe","valor":70,"unidade":"USD"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('kit','Kit, água e cortesia');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('kit',1,'{"colunas":[{"chave":"agua","nome":"Água USD","tipo":"numero"},{"chave":"cortesia","nome":"Cortesia USD","tipo":"numero"},{"chave":"ticket","nome":"Kit básico USD","tipo":"numero"}],"linhas":[{"id":"economico","nome":"Econômico","agua":1,"cortesia":3,"ticket":15},{"id":"padrao","nome":"Padrão","agua":1,"cortesia":5,"ticket":15},{"id":"premium","nome":"Premium","agua":2,"cortesia":7.5,"ticket":15},{"id":"vip","nome":"VIP","agua":2,"cortesia":10,"ticket":15}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('gorjetas','Gorjetas sugeridas');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('gorjetas',1,'{"colunas":[{"chave":"valor","nome":"Valor","tipo":"numero"},{"chave":"unidade","nome":"Unidade","tipo":"texto"}],"linhas":[{"id":"motorista","nome":"Motorista / cliente / dia","valor":2,"unidade":"USD"},{"id":"guia","nome":"Guia / cliente / dia","valor":4,"unidade":"USD"},{"id":"assistente","nome":"Assistente / cliente / dia","valor":2,"unidade":"USD"},{"id":"backoffice","nome":"Back office / cliente / dia","valor":5,"unidade":"USD"},{"id":"premium_vip","nome":"Adicional Premium/VIP por categoria","valor":3,"unidade":"USD"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('fatores','Fatores de cálculo');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('fatores',1,'{"colunas":[{"chave":"valor","nome":"Valor","tipo":"numero"},{"chave":"unidade","nome":"Unidade","tipo":"texto"}],"linhas":[{"id":"regional","nome":"Carro fora de Seul","valor":0.2,"unidade":"adicional"},{"id":"vip_carro","nome":"Carro VIP","valor":0.1,"unidade":"adicional"},{"id":"vip_transfer","nome":"Transfer VIP","valor":0.2,"unidade":"adicional"},{"id":"carro_transfer","nome":"Transfer no dia com carro","valor":0.15,"unidade":"adicional"},{"id":"sem_guia","nome":"Motorista em inglês sem guia","valor":0.2,"unidade":"adicional"},{"id":"evento","nome":"Evento especial","valor":0.1,"unidade":"adicional"},{"id":"jinhae","nome":"Jinhae carro","valor":100,"unidade":"USD"},{"id":"meia","nome":"Até 4h","valor":0.6,"unidade":"fator","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"intermediaria","nome":"Mais de 4h até 6h","valor":0.8,"unidade":"fator","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"hora_extra","nome":"Hora extra carro","valor":0.08,"unidade":"adicional"},{"id":"ktx_feriado","nome":"KTX em feriado","valor":0.2,"unidade":"adicional","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"hotel","nome":"Segurança hotel","valor":0.05,"unidade":"adicional"},{"id":"voo_equipe","nome":"Segurança voo equipe","valor":0.15,"unidade":"adicional"},{"id":"onibus","nome":"Intermediação ônibus","valor":0.15,"unidade":"adicional"},{"id":"influencer","nome":"Comissão Influencer","valor":0.05,"unidade":"percentual"},{"id":"processamento","nome":"Processamento cancelamento","valor":0.1,"unidade":"percentual"},{"id":"espera","nome":"Espera após 90 minutos","valor":0.1,"unidade":"adicional","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"feriado_janela","nome":"Janela de feriado antes/depois","valor":2,"unidade":"dias","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"temporada_feriado","nome":"Temporada de feriado","valor":1.2,"unidade":"fator"},{"id":"onibus_fds","nome":"Ônibus fim de semana/feriado","valor":1.2,"unidade":"fator"},{"id":"pernoite_especial","nome":"Pernoite sex/dom/véspera","valor":0.2,"unidade":"adicional"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('pagamentos','Pagamento e câmbio');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('pagamentos',1,'{"colunas":[{"chave":"valor","nome":"Valor","tipo":"numero"},{"chave":"unidade","nome":"Unidade","tipo":"texto"}],"linhas":[{"id":"cartao","nome":"Cartão","valor":1.05,"unidade":"fator","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"pix","nome":"PIX","valor":1.035,"unidade":"fator"},{"id":"cambio","nome":"Segurança câmbio KRW/USD","valor":1.1,"unidade":"fator"},{"id":"sinal","nome":"Sinal inicial","valor":0.2,"unidade":"percentual"},{"id":"iva","nome":"IVA (desligado por padrão)","valor":0.1,"unidade":"percentual","provisorio":"Padrão provisório — docs/padroes-provisorios.md"},{"id":"taxa_roteiro","nome":"Taxa de roteiro (suspensa)","valor":0,"unidade":"USD"},{"id":"margem_minima","nome":"Margem mínima","valor":0.1,"unidade":"percentual","provisorio":"Padrão provisório — docs/padroes-provisorios.md"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('porte_onibus','Porte do ônibus');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('porte_onibus',1,'{"colunas":[{"chave":"valor","nome":"Valor","tipo":"numero"},{"chave":"unidade","nome":"Unidade","tipo":"texto"}],"linhas":[{"id":"16","nome":"16 lugares","valor":0.8,"unidade":"fator"},{"id":"25","nome":"25 lugares","valor":0.7,"unidade":"fator"},{"id":"45","nome":"45 lugares","valor":1,"unidade":"fator"},{"id":"28","nome":"Limousine 28 lugares","valor":1.3,"unidade":"fator"}]}'::jsonb);

--> statement-breakpoint
INSERT INTO tabelas_referencia (codigo,titulo) VALUES ('onibus_distancia','Ônibus por distância e duração');
--> statement-breakpoint
INSERT INTO versoes_referencia (tabela,versao,dados) VALUES ('onibus_distancia',1,'{"colunas":[{"chave":"km","nome":"Menos de km","tipo":"numero"},{"chave":"dia1","nome":"Um dia USD","tipo":"numero"},{"chave":"dia2","nome":"Dois dias USD","tipo":"numero"},{"chave":"dia3","nome":"Três dias USD","tipo":"numero"},{"chave":"dia4","nome":"Quatro dias USD","tipo":"numero"}],"linhas":[{"id":"200","nome":"Até 200 km","km":200,"dia1":468.148,"dia2":862.222,"dia3":1256.3,"dia4":1626.67},{"id":"300","nome":"Até 300 km","km":300,"dia1":629.63,"dia2":1029.63,"dia3":1423.7,"dia4":1794.07},{"id":"400","nome":"Até 400 km","km":400,"dia1":802.963,"dia2":1197.04,"dia3":1591.11,"dia4":1961.48},{"id":"500","nome":"Até 500 km","km":500,"dia1":936.296,"dia2":1330.37,"dia3":1724.44,"dia4":2094.81},{"id":"600","nome":"Até 600 km","km":600,"dia1":1084.44,"dia2":1478.52,"dia3":1872.59,"dia4":2242.96},{"id":"700","nome":"Até 700 km","km":700,"dia1":1232.59,"dia2":1626.67,"dia3":2020.74,"dia4":2391.11},{"id":"800","nome":"Até 800 km","km":800,"dia1":1380.74,"dia2":1774.81,"dia3":2168.89,"dia4":2539.26},{"id":"900","nome":"Até 900 km","km":900,"dia1":1528.89,"dia2":1922.96,"dia3":2317.04,"dia4":2687.41}]}'::jsonb);
