export type IdiomaInterface = "pt" | "ko";

const coreano = {
  "Alternativas de transporte": "교통 대안",
  "Estimativa: informe o custo real antes de enviar":
    "예상 금액: 발송 전 실제 원가를 입력하세요",
  "Capacidade de conforto excedida": "권장 승차 인원 초과",
  "Distância contratada km": "계약 거리 km",
  "Duração contratada dias": "계약 일수",
  "Registre a contratação contínua uma vez; nos demais dias zere a quantidade do ônibus.":
    "연속 계약은 한 번 기록하고 나머지 날의 버스 수량을 0으로 설정하세요.",
  "Linhas com padrões provisórios": "임시 기준 항목",
  "Adicionar transfer": "송영 추가",
  Selecionar: "선택",

  Papel: "역할",
  Guia: "가이드",
  Assistente: "보조",
  "Profissional necessário": "필수 담당자",
  Nenhum: "없음",
  "Guia do dia": "당일 가이드",
  "Assistente do dia": "당일 보조",
  ocupada: "일정 있음",
  "está ocupada": "일정이 있습니다",
  "não fala o idioma de guiamento": "안내 언어를 구사하지 않습니다",
  "Profissionais e disponibilidade": "담당자 및 일정",
  "Idiomas (códigos)": "언어 코드",
  Especialidades: "전문 분야",
  "Salvar profissional": "담당자 저장",
  Profissional: "담당자",
  "Viagem ID": "여행 ID",
  Início: "시작",
  Fim: "종료",
  "Confirmar alocação": "배정 확정",

  "Cobrar elaboração de roteiro": "일정 작성 수수료 부과",
  "Taxa de elaboração USD": "일정 작성 수수료 USD",
  "Taxa paga": "수수료 결제됨",
  "Registrar pagamento da taxa": "수수료 결제 기록",
  "Desconto da elaboração": "일정 작성 수수료 공제",

  "Registrar aceite": "수락 기록",
  "Versão aceita": "수락 버전",
  "Proposta fora da validade; confira os preços":
    "제안서 유효기간이 지났습니다. 가격을 확인하세요",
  "Opção aceita": "수락 옵션",
  Selecione: "선택",
  "Aceito em (ISO)": "수락 시각 (ISO)",
  "Confirmar aceite": "수락 확정",
  "Preço acordado": "합의 가격",

  "Abrir proposta": "제안서 열기",
  "Copiar resumo B2B": "B2B 요약 복사",
  "Texto copiado": "텍스트 복사됨",
  "Condições da proposta": "제안서 조건",
  "Sinal (%)": "계약금 (%)",
  "Saldo: dias antes da viagem": "잔금: 여행 전 일수",
  "Validade em dias": "유효기간 (일)",
  "IVA (%)": "부가세 (%)",
  Incluso: "포함 사항",
  "Não incluso": "불포함 사항",
  "Condições de cancelamento": "취소 조건",
  "Formas de pagamento": "결제 방법",
  "Dados bancários": "은행 정보",
  "Notas para a agência": "여행사 참고 사항",
  "Proposta genérica": "일반 제안서",
  "Detalhamento de preços": "가격 상세",
  "Por dia": "일차별",
  "Por serviço": "서비스별",

  "Sem resposta": "응답 없음",
  "Versão congelada": "확정된 버전",
  "Iniciar nova versão": "새 버전 시작",
  "Destinatário do envio": "발송 수신자",
  "Canal do envio": "발송 채널",
  "Registrar envio": "발송 기록",
  "Envios de proposta": "제안서 발송 이력",

  Notificações: "알림",
  "Ativar notificações": "알림 활성화",
  "Notificações não autorizadas": "알림 권한이 허용되지 않음",
  "Notificações ativadas": "알림 활성화됨",
  "Não foi possível ativar notificações": "알림을 활성화할 수 없습니다",

  "Pedido do cliente": "고객 요청",
  "Preparar rascunho": "초안 준비",
  "Revisão do pedido": "요청 검토",
  dias: "일",
  "Confirmar pedido": "요청 확정",
  "Pedido confirmado": "요청 확정 완료",
  "Confirmar substitui os dias da primeira opção e atualiza datas e viajantes na Viagem.":
    "확정하면 첫 번째 옵션의 일정을 바꾸고 여행 날짜와 여행자를 업데이트합니다.",

  "Exportar Excel": "Excel 내보내기",
  "Arquivo Excel": "Excel 파일",
  "Revisar importação": "가져오기 검토",
  "Aplicar importação": "가져오기 적용",
  "Agência: viagem abaixo de 3 dias": "여행사: 3일 미만 여행",
  "Jeju: menos de 2 dias de guia": "제주: 가이드 일정 2일 미만",
  "Carro próprio não recomendado para VIP": "VIP에 자가 차량을 권장하지 않음",

  "Copiar opção": "옵션 복사",
  "Categoria da opção": "옵션 서비스 등급",
  "Custo real da linha USD": "항목 실제 원가 USD",
  "Margem estimada": "예상 이익률",
  "não verificável": "검증 불가",
  "Motivo da margem": "이익률 사유",
  "Comissão Influencer": "인플루언서 수수료",
  "Margem abaixo de 10%; registre o motivo":
    "이익률 10% 미만: 사유를 기록하세요",

  "Hotel da linha": "항목 호텔",
  Quartos: "객실 수",
  Noites: "숙박일 수",
  "Impostos do hotel (%)": "호텔 세금 (%)",
  "Café por quarto e noite": "객실 1박당 조식",
  Ocupação: "객실 인원",
  Duplo: "2인실",
  Single: "1인실",
  "Fonte da cotação": "견적 출처",
  "Data da cotação": "견적 일자",
  "Viajantes do quarto": "객실 여행자",
  "Reservado por terceiro, sem cobrança": "제3자 예약, 요금 없음",
  "Adicionar hotel": "호텔 추가",

  "Viajantes do dia": "당일 여행자",
  "Cobrar por viajante": "여행자별 요금 적용",
  "Viajantes desta linha": "이 항목의 여행자",
  "Tarifa infantil USD": "아동 요금 USD",
  "Idade máxima infantil": "아동 최대 나이",
  "Tarifa sênior USD": "경로 요금 USD",
  "Fornecedor confirma elegibilidade sênior destes viajantes":
    "공급업체가 해당 여행자의 경로 할인 자격을 확인함",
  "Confirmar remoção": "삭제 확인",
  "Dias e linhas afetados": "영향받는 일차 및 항목",
  Cancelar: "취소",

  "Item de referência": "기준 항목",
  "Adicionar item": "항목 추가",
  "Mostrar gorjeta sugerida": "권장 팁 표시",
  "Gorjeta sugerida, não incluída": "권장 팁 (가격에 미포함)",
  "Custo do voo USD": "항공편 원가 USD",
  "Kit Busan": "부산 입장권 키트",
  "Voo Jeju": "제주 항공편",
  "Voo da equipe": "직원 항공편",
  "KTX do guia": "가이드 KTX",
  "Kit de ingressos": "입장권 키트",
  Água: "생수",
  Cortesia: "증정품",

  "Malas de 23 kg": "23kg 수하물",
  "Bagagem de mão": "기내 수하물",
  "Veículo sugerido": "권장 차량",
  "Veículo do dia": "당일 차량",
  Ônibus: "버스",
  "Usar sugestão": "권장값 사용",
  "Porte do ônibus": "버스 규모",
  "Assentos insuficientes": "좌석 부족",
  "Veículo maior ou segundo veículo": "더 큰 차량 또는 두 번째 차량",
  "Bagagem excede a referência de conforto; confirme veículo maior ou caminhão de bagagem":
    "수하물이 적정 용량을 초과합니다. 더 큰 차량 또는 수하물 트럭을 확인하세요",
  "Transporte autorizado pelo cliente": "고객이 승인한 교통수단",
  "Veículo maior": "더 큰 차량",
  "Segundo veículo": "두 번째 차량",
  "Caminhão de bagagem": "수하물 트럭",
  "Transporte público": "대중교통",

  "Valor unitário": "단가",
  "Moeda da linha": "항목 통화",
  "Unidades da moeda por USD": "USD당 통화 단위",
  "Data do câmbio": "환율 기준일",
  "Fonte do câmbio": "환율 출처",

  "Atualizar referências": "기준표 업데이트",
  "Informe o motivo do ajuste": "조정 사유를 입력하세요",
  "Categoria do orçamento": "견적 서비스 등급",
  "Início do serviço": "서비스 시작 시간",
  "Fim do serviço": "서비스 종료 시간",
  "Informe os horários do período": "서비스 시작 및 종료 시간을 입력하세요",
  "Valor sugerido": "권장 가격",
  "Motivo do ajuste": "조정 사유",

  Orçamento: "견적",
  Orçamentos: "견적 목록",
  "Criar orçamento": "견적 작성",
  "Voltar à viagem": "여행으로 돌아가기",
  "Contagem dos dias": "일차 시작",
  Dia: "일차",
  "Margem (%)": "마진 (%)",
  Data: "날짜",
  "Cidade ou trecho": "도시 또는 구간",
  Período: "기간",
  "Dia completo": "종일",
  "Meio período": "반일",
  "Dia livre": "자유 일정",
  Deslocamento: "이동",
  Manhã: "오전",
  Almoço: "점심",
  Tarde: "오후",
  "Descrição da linha": "항목 설명",
  Quantidade: "수량",
  "Valor unitário USD": "단가 USD",
  Grupo: "분류",
  Total: "합계",
  Serviços: "서비스",
  Terceiros: "외부 서비스",
  "Remover linha": "항목 삭제",
  "Adicionar linha": "항목 추가",
  "Inserir dia após este": "다음 일차 추가",
  "Mover dia para cima": "일차 위로 이동",
  "Remover dia": "일차 삭제",
  Margem: "마진",
  Hotéis: "호텔",
  "Preço calculado": "계산 가격",
  "Preço enviado": "제시 가격",
  Diferença: "차액",
  "Por pessoa pagante": "유료 고객 1인당",
  "Preço enviado USD": "제시 가격 USD",
  "Salvar orçamento": "견적 저장",
  "Orçamento salvo": "견적 저장 완료",

  "Tabelas de referência": "기준표",
  Versão: "버전",
  Referência: "기준",
  "Padrão provisório": "잠정 기준",
  "Adicionar referência": "기준 추가",
  "Nome da nova referência": "새 기준 이름",
  "Salvar nova versão": "새 버전 저장",
  "Histórico de versões": "버전 이력",
  "Referência inicial": "초기 기준",
  "Valores vazios: a informar ou serviço não oferecido.":
    "빈 값: 확인 필요 또는 제공하지 않는 서비스.",
  "Guia e Assistente": "가이드 및 보조 가이드",
  "Guia USD": "가이드 USD",
  "Assistente USD": "보조 가이드 USD",
  "Temporada CoreaLux": "CoreaLux 성수기",
  "Frota e tarifas": "차량 및 요금",
  "Eventos especiais": "특별 행사",
  "Feriados nacionais coreanos": "한국 공휴일",
  "Pagamento e câmbio": "결제 및 환율",

  "Resposta do cliente": "고객 답변",
  "Ainda pensando": "검토 중",
  "Pediu mudanças": "변경 요청",
  Recusou: "거절",
  Cancelamento: "취소",
  "Motivo da resposta": "답변 사유",
  "Registrar resposta do cliente": "고객 답변 기록",
  "Histórico de etapas": "단계 이력",
  "Motivo da correção": "정정 사유",
  "Corrigir fato": "기록 정정",
  "Correção de etapa": "단계 정정",
  "Orçamento criado": "견적 생성",
  "Nova versão": "새 버전",
  Aceitou: "수락",

  "Minhas Tarefas": "내 작업",
  Título: "제목",
  Descrição: "설명",
  "Responsável da tarefa": "작업 담당자",
  "Prazo da tarefa": "작업 기한",
  "Criar tarefa": "작업 생성",
  Cópias: "참조",
  Aberta: "진행 중",
  "Concluir tarefa": "작업 완료",
  Reabrir: "다시 열기",
  "Motivo do cancelamento": "취소 사유",
  "Cancelar tarefa": "작업 취소",
  "Histórico da tarefa": "작업 이력",
  Criada: "생성됨",
  Reaberta: "다시 열림",
  Transferida: "이관됨",
  Todas: "전체",
  Atrasadas: "기한 초과",
  Filtrar: "필터",
  Tarefas: "작업",

  Páginas: "페이지",
  "Página anterior": "이전 페이지",
  "Próxima página": "다음 페이지",
  Participantes: "참여 직원",
  Participante: "참여자",
  "Adicionar participante": "참여자 추가",
  Removido: "제외됨",
  "Remover participante": "참여자 제외",
  "Viagens relacionadas": "관련 여행",
  "Viagem relacionada": "관련 여행",
  "Vincular viagem": "여행 연결",
  Desvincular: "연결 해제",
  "Desejos e aprovações": "요청 및 승인",
  "Desejo do cliente": "고객 요청",
  "Adicionar desejo": "요청 추가",
  Descartado: "제외됨",
  "Aprovado por": "승인자",
  Desejado: "요청됨",
  Aprovar: "승인",
  "Descartar desejo": "요청 제외",

  "Perfil do cliente": "고객 프로필",
  "Cliente conhecido": "기존 고객",
  "Aniversário durante a viagem": "여행 중 생일",
  Nascimento: "생년월일",
  Preferências: "선호 사항",
  "Como o roteiro foi recebido": "일정에 대한 의견",
  "Salvar perfil": "프로필 저장",

  "Formulário revogado": "양식 링크가 폐기되었습니다",
  "Respostas recebidas": "받은 응답",
  "Arquivo de planejamento": "여행 계획 파일",
  "Adicionar respostas": "응답 추가",

  "Respostas conflitantes": "상충하는 응답",
  Registrado: "등록된 값",
  Recebido: "받은 값",
  "Usar resposta": "응답 적용",
  "Manter registrado": "등록된 값 유지",

  "Formulário de planejamento": "여행 계획 양식",
  "Enviar formulário": "양식 링크 만들기",
  "Revogar formulário": "양식 링크 폐기",
  "Abrir formulário": "양식 열기",

  "Modelos de primeira resposta": "첫 응답 템플릿",
  "Use {dados_faltantes} para pedir apenas o que ainda falta.":
    "아직 없는 정보만 요청하려면 {dados_faltantes}를 사용하세요.",
  Modelo: "템플릿",
  "Primeira resposta": "첫 응답",
  "Copiar primeira resposta": "첫 응답 복사",
  "A informar": "입력 필요",

  Idades: "나이",
  Hotel: "호텔",
  Mobilidade: "이동 제한",
  "O que você não come": "먹지 않는 음식",
  "Nível de restaurante": "식당 수준",
  Ritmo: "여행 속도",
  Interesses: "관심사",
  "Pontos que gostaria": "방문 희망 장소",
  "Dados faltantes": "미입력 정보",
  "Mensagem para pedir dados": "정보 요청 메시지",
  Copiado: "복사됨",
  "Copiar mensagem": "메시지 복사",
  Planejamento: "여행 계획",
  "Endereço do hotel": "호텔 주소",
  "Salvar planejamento": "여행 계획 저장",

  Viajantes: "여행자 목록",
  Criança: "어린이",
  Bebê: "유아",
  Adulto: "성인",
  Pagamento: "요금 구분",
  Pagante: "유료",
  Gratuidade: "무료",
  "Faixa etária": "연령대",
  Idade: "나이",
  Salvar: "저장",
  "Adicionar viajante": "여행자 추가",

  Remover: "삭제",
  Seul: "서울",
  Busan: "부산",
  Jeju: "제주",

  "Opções conhecidas": "등록된 선택 항목",
  Campo: "필드",
  Nome: "이름",
  Tipo: "유형",
  Alterar: "변경",
  Regular: "기본 항목",
  Exceção: "예외",
  Renomear: "이름 변경",
  "Tornar regular": "기본 항목으로 등록",
  "Mesclar com": "병합 대상",
  Mesclar: "병합",

  "Outro…": "기타…",
  Contatos: "연락처",
  Lead: "리드",
  "Em orçamento": "견적 작성 중",
  "Proposta enviada": "제안서 발송 완료",
  "Em negociação": "협의 중",
  Confirmada: "확정",
  "Em viagem": "여행 중",
  Concluída: "완료",
  Perdida: "수주 실패",
  Cancelada: "취소",
  Descartada: "제외",
  "Interep/Operadora": "Interep/여행 도매사",
  Agência: "여행사",
  "Cliente final": "직접 고객",
  Influencer: "인플루언서",
  Econômico: "이코노미",
  Padrão: "스탠다드",
  Premium: "프리미엄",
  VIP: "VIP",
  Instagram: "인스타그램",
  Site: "웹사이트",
  Indicação: "소개",
  Operadora: "여행 도매사",
  Influenciador: "인플루언서",
  Outra: "기타",
  Português: "포르투갈어",
  Espanhol: "스페인어",
  Inglês: "영어",
  Francês: "프랑스어",
  "CoreaLux (B2B)": "CoreaLux (B2B)",
  "Guia na Coreia (B2C)": "Guia na Coreia (B2C)",
  Quem: "연락 대상",
  "Nome do contato": "연락처 이름",
  Telefone: "전화번호",
  Solicitante: "요청자",
  Viajante: "여행자",
  "+ Contato": "+ 연락처",
  "Canal e origem": "판매 채널 및 유입 경로",
  "Canal comercial": "판매 채널",
  Marca: "브랜드",
  Origem: "유입 경로",
  "Indicado por": "소개자",
  "Cadeia comercial": "판매 경로",
  "O que especificou": "요청 내용",
  Viagem: "여행",
  Chegada: "도착",
  Partida: "출발",
  Cidades: "도시",
  Pagantes: "유료 인원",
  Gratuidades: "무료 인원",
  Adultos: "성인",
  "Idades das crianças": "어린이 나이",
  Bebês: "유아",
  "Categoria de atendimento": "서비스 등급",
  "Idioma do cliente": "고객 언어",
  "Idioma de guiamento": "가이드 언어",
  Nota: "메모",
  "Criando…": "생성 중…",
  "Criar viagem": "여행 만들기",
  "Seul, Busan, Jeju": "서울, 부산, 제주",
  "O que foi pedido, valores falados…": "요청 사항, 협의 금액…",
  "Sem resposta há mais de 24h": "24시간 이상 응답 없음",
  Categoria: "등급",
  Idiomas: "언어",
  "Cliente:": "고객:",
  "· Guiamento:": "· 가이드:",
  Datas: "날짜",
  Pessoas: "인원",
  "Meios de contato": "연락 수단",
  "Próximas ações": "다음 할 일",
  "Respondi o contato": "첫 응답 완료",
  Descartar: "제외",
  "Imprensa, spam, parceria…": "언론, 스팸, 제휴…",
  "Motivo do descarte": "제외 사유",
  Notas: "메모",
  "Nova nota": "새 메모",
  "Negociação, pedidos, valores falados…": "협의, 요청 사항, 금액…",
  Adicionar: "추가",
  "Buscar viagem": "여행 검색",
  "Código, contato, telefone, e-mail ou agência":
    "코드, 연락처, 전화번호, 이메일 또는 여행사",
  WhatsApp: "WhatsApp",
  "WhatsApp pessoal": "개인 WhatsApp",
  "Respond.io": "Respond.io",
  "Telefone/áudio": "전화/음성",
  Videochamada: "영상 통화",
  Formulário: "양식",
  agora: "현재",
  prazo: "기한",
  "pagantes,": "유료 인원,",
  "gratuidades ·": "무료 인원 ·",
  adultos: "성인",
  "crianças de": "어린이 나이",
  anos: "세",
  "bebê(s)": "유아",
  viagem: "여행",
  viagens: "여행",
  "sem resposta há mais de 24h": "24시간 이상 응답 없음",
  "Atenção:": "주의:",
  "já está aberta com o mesmo contato por outra cadeia comercial.":
    "동일 연락처에 대해 다른 판매 경로의 여행이 이미 진행 중입니다.",
  "Responder o primeiro contato": "첫 연락에 응답",
  solicitante: "요청자",
  viajante: "여행자",
  agencia: "여행사",
  operadora: "여행 도매사",
  "E-mail ou senha incorretos": "이메일 또는 비밀번호가 올바르지 않습니다",
  "Tente novamente em 15 minutos": "15분 후 다시 시도하세요",
  "Toda Viagem nasce com um Responsável.": "여행에는 담당자가 필요합니다.",
  "Informe ao menos um Contato.": "연락처를 하나 이상 입력하세요.",
  "Viagem não encontrada.": "여행을 찾을 수 없습니다.",
  "Só um lead pode ser descartado.": "리드 단계만 제외할 수 있습니다.",
  "Informe o motivo.": "사유를 입력하세요.",
  "Algo deu errado": "오류가 발생했습니다",
  Erro: "오류",

  Pipeline: "파이프라인",
  "Nova viagem": "새 여행",
  Buscar: "검색",
  Sair: "로그아웃",
  "Idioma da interface": "인터페이스 언어",
  "E-mail": "이메일",
  Senha: "비밀번호",
  "Entrando…": "로그인 중…",
  Entrar: "로그인",
  Código: "코드",
  Contato: "연락처",
  Etapa: "단계",
  Canal: "판매 채널",
  Responsável: "담당자",
  "Próxima ação": "다음 할 일",
  Prazo: "기한",
  "Nenhuma viagem aberta.": "진행 중인 여행이 없습니다.",
} as const;

export type ChaveTraducao = keyof typeof coreano;
export function traduzir(
  idioma: IdiomaInterface,
  chave: ChaveTraducao,
): string {
  return idioma === "ko" ? coreano[chave] : chave;
}

export function traduzirMensagem(
  idioma: IdiomaInterface,
  mensagem: string,
): string {
  return idioma === "ko" && Object.hasOwn(coreano, mensagem)
    ? coreano[mensagem as ChaveTraducao]
    : mensagem;
}
